In [1]:
import pandas as pd
import numpy as np

In [3]:
a=np.random.randint(20,60,15)

In [5]:
a

array([50, 36, 24, 49, 20, 50, 46, 48, 31, 29, 50, 36, 30, 59, 44])

In [7]:
a[-5:-12:-1]

array([50, 29, 31, 48, 46, 50, 20])

In [9]:
a.ndim

1

In [11]:
a[-4]

36

In [25]:

b=np.random.randint(45,78,(7,8))
b

array([[76, 47, 66, 57, 77, 72, 76, 53],
       [77, 56, 53, 69, 76, 63, 69, 60],
       [77, 49, 53, 65, 59, 77, 65, 55],
       [48, 45, 50, 46, 75, 55, 48, 64],
       [57, 73, 63, 63, 58, 62, 57, 53],
       [68, 54, 65, 62, 70, 76, 63, 52],
       [53, 54, 58, 66, 71, 46, 45, 75]])

In [23]:
b[0]

array([50, 60, 50, 74, 50, 45, 74, 77])

In [19]:
b[-1]# last row

array([60, 66, 67, 55, 46, 73, 49, 57])

In [27]:
b[:,3]

array([57, 69, 65, 46, 63, 62, 66])

In [29]:
b[:,7] # 7th column

array([53, 60, 55, 64, 53, 52, 75])

In [31]:
b[1,3]

69

In [35]:
b[5,6] #5th row and 6th column

63

In [43]:
b[2,1:6]

array([49, 53, 65, 59, 77])

array [row_start : row-end : row-step , col_start : col_end : col_step]]

In [46]:
b

array([[76, 47, 66, 57, 77, 72, 76, 53],
       [77, 56, 53, 69, 76, 63, 69, 60],
       [77, 49, 53, 65, 59, 77, 65, 55],
       [48, 45, 50, 46, 75, 55, 48, 64],
       [57, 73, 63, 63, 58, 62, 57, 53],
       [68, 54, 65, 62, 70, 76, 63, 52],
       [53, 54, 58, 66, 71, 46, 45, 75]])

In [50]:
b[1:6]

array([[77, 56, 53, 69, 76, 63, 69, 60],
       [77, 49, 53, 65, 59, 77, 65, 55],
       [48, 45, 50, 46, 75, 55, 48, 64],
       [57, 73, 63, 63, 58, 62, 57, 53],
       [68, 54, 65, 62, 70, 76, 63, 52]])

In [64]:
b[1:6:2,1:6]

array([[56, 53, 69, 76, 63],
       [45, 50, 46, 75, 55],
       [54, 65, 62, 70, 76]])

In [69]:
b[2:5,2:6]

array([[53, 65, 59, 77],
       [50, 46, 75, 55],
       [63, 63, 58, 62]])

In [73]:
b[1:6:2,1:8:3]

array([[56, 76, 60],
       [45, 75, 64],
       [54, 70, 52]])