In [1]:
h=[30,20,5,8,9]
h

[30, 20, 5, 8, 9]

In [19]:
d=[]
for i in h:
    d.append(i+7)
    

In [21]:
d

[37, 27, 12, 15, 16]

In [23]:
s=(6,2,3,9,7,5,8)
s

(6, 2, 3, 9, 7, 5, 8)

In [37]:
y=list(s)
k=[]
for i in y:
    k.append(i**2)
s=tuple(k)
s

(36, 4, 9, 81, 49, 25, 64)

In [41]:
s

(36, 4, 9, 81, 49, 25, 64)

In [43]:
for i in s:
    if i>50:
        print(i)

81
64


In [53]:
k=[]
for i in s:
    if i>50:
        k.append(i)

In [55]:
k

[81, 64]

In [63]:
import numpy as np
arr=np.array([20,50,30,70,80,40,36,54,23,98])


In [65]:
arr

array([20, 50, 30, 70, 80, 40, 36, 54, 23, 98])

In [67]:
t=arr+7

In [69]:
t

array([ 27,  57,  37,  77,  87,  47,  43,  61,  30, 105])

In [71]:
arr*5

array([100, 250, 150, 350, 400, 200, 180, 270, 115, 490])

In [73]:
arr>50

array([False, False, False,  True,  True, False, False,  True, False,
        True])

In [75]:
arr%4

array([0, 2, 2, 2, 0, 0, 0, 2, 3, 2], dtype=int32)

In [79]:
arr[4:8:2]

array([80, 36])

In [81]:
arr[arr>50] # elements satisfying codnition

array([70, 80, 54, 98])

In [88]:
n=[]
for i in range(len(k)):
    if k[i]>50:
        n.append(i)
n

[0, 1]

In [90]:
np.where(arr>50)  # indesex of elemlnets satisfying condiition

(array([3, 4, 7, 9], dtype=int64),)